# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18.x
#     commands:
      # - echo Install phase started.
      # - npm install -g npm
      # - npm install -g @nestjs/cli
      # - npm ci
      # - echo Install phase completed.

#   pre_build:
#     commands:
#       - echo Pre-Build phase started.
#       - echo "Node.js version:" $(node -v)
#       - echo Pre-Build phase completed.

#   build:
#     commands:
#       - echo Build phase started.
#       - npm run build
#       - echo Build phase completed.
#       - echo Test phase started.
#       - npm run test
#       - echo Test phase completed.

# artifacts:
#   files:
#     - 'dist/**/*'
#     - .ebextensions/*
#     - package.json
#   base-directory: './'

version: 0.2

env:
  secrets-manager:
    DOCKERHUB_TOKEN: "docker:token"
    DOCKERHUB_USERNAME: "docker:username"
    DOCKERHUB_TEST: "docker:docker_test"
    # DOCKERHUB_PASS: "/docker:PASSWORD"
    # DOCKERHUB_USERNAME: "/docker:USERNAME"
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo Install phase started.
      - npm install -g npm
      - npm install -g @nestjs/cli
      - npm ci
      # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 & timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Install phase completed.
  pre_build:
    commands:
      - echo Pre-Build phase started.
      - echo "Node.js version:" $(node -v)
      
      - SECRET=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-central-1:544564125819:secret:docker-zx2yH8 --query SecretString --output text)
      - echo "All keys in secret:" $SECRET

      - DOCKER_TEST=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-central-1:544564125819:secret:docker-zx2yH8 --query SecretString --output text | jq -r .DOCKER_TEST)
      - echo "DOCKER_TEST:" $DOCKER_TEST
 
      - USERNAME=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-central-1:544564125819:secret:docker-zx2yH8 --query SecretString --output text | jq -r .USERNAME)
      - USERNAME2=$(aws secretsmanager get-secret-value --secret-id $USERNAME | jq -r ".SecretString" | jq -r ".ssh_key")
      - echo "USERNAME:" $USERNAME
      - echo "USERNAME2:" $USERNAME2

      - TOKEN=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-central-1:544564125819:secret:docker-zx2yH8 --query SecretString --output text | jq -r .TOKEN)
      - echo "USERNAME:" $USERNAME
      - echo "TOKEN:" $TOKEN
      - echo "DOCKERHUB_TOKEN:" $DOCKERHUB_TOKEN
      - echo "DOCKERHUB_USERNAME:" $DOCKERHUB_USERNAME
      - echo "DOCKERHUB_TEST:" $DOCKERHUB_TEST

      - echo log in into Docker hub.
      - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
      # - echo dckr_pat_HyjVfHSApR74uYiEfzDKKtJmHNA | docker login --username vladisb --password-stdin

      - echo log in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      # - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $REPO_DOMAIN
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 544564125819.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_URI=544564125819.dkr.ecr.eu-central-1.amazonaws.com/course-mangement
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Pre-Build phase completed.
  build:
    commands:
      - echo Build phase started on `date`.
      - npm run build
      - echo nest build phase completed.

      # - echo Test phase started.
      # - npm run test
      # - echo Test phase completed.

      - echo Building the Docker image.
      - echo $REPOSITORY_URI 
      - echo $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker build -t $REPOSITORY_URI:latest .
      - echo $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Building the Docker image complited.
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo write definitions file...
      - printf '[{"name":"course-mangement-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

