# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18.x
#     commands:
      # - echo Install phase started.
      # - npm install -g npm
      # - npm install -g @nestjs/cli
      # - npm ci
      # - echo Install phase completed.

#   pre_build:
#     commands:
#       - echo Pre-Build phase started.
#       - echo "Node.js version:" $(node -v)
#       - echo Pre-Build phase completed.

#   build:
#     commands:
#       - echo Build phase started.
#       - npm run build
#       - echo Build phase completed.
#       - echo Test phase started.
#       - npm run test
#       - echo Test phase completed.

# artifacts:
#   files:
#     - 'dist/**/*'
#     - .ebextensions/*
#     - package.json
#   base-directory: './'

version: 0.2

env:
  variables:
    TEST_VALUE: "test_value"
  secrets-manager:
    DOCKERHUB_TOKEN: "docker:token"
    DOCKERHUB_USERNAME: "docker:username"
    # DOCKERHUB_PASS: "/docker:PASSWORD"
    # DOCKERHUB_USERNAME: "/docker:USERNAME"
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo Install phase started.
      - npm install -g npm
      - npm install -g @nestjs/cli
      - npm ci
      # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 & timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Install phase completed.
  pre_build:
    commands:
      - echo Pre-Build phase started.
      - echo "Node.js version:" $(node -v)

      - echo log in into Docker hub.
      - echo "TEST_VALUE:" $TEST_VALUE
      - echo "DOCKERHUB_USERNAME:" $DOCKERHUB_USERNAME
      - echo "DOCKERHUB_TOKEN:" $DOCKERHUB_TOKEN

      - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
      # - echo dckr_pat_HyjVfHSApR74uYiEfzDKKtJmHNA | docker login --username vladisb --password-stdin

      - echo Pre-Build phase completed.
  build:
    commands:
      - echo Build phase started on `date`.
      - npm run build
      - echo nest build phase completed.

      # - echo Test phase started.
      # - npm run test
      # - echo Test phase completed.


